# Generated by Django 4.0.2 on 2022-08-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='databases',
            options={'verbose_name_plural': 'Databases'},
        ),
        migrations.AlterModelOptions(
            name='frameworks',
            options={'verbose_name_plural': 'Frameworks'},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='tools',
            options={'verbose_name_plural': 'Tools'},
        ),
        migrations.AddField(
            model_name='comments',
            name='content_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
