# Generated by Django 4.0.2 on 2022-08-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariga', '0002_alter_comments_options_alter_databases_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databases',
            name='database',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='frameworks',
            name='framework',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='tool',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
