# Generated by Django 4.0.2 on 2022-08-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariga', '0006_alter_projects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
