# Generated by Django 4.0.2 on 2022-08-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariga', '0008_projects_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(default='Great Project', max_length=1000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='details',
            field=models.TextField(max_length=1000),
        ),
    ]
