# Generated by Django 4.0.2 on 2022-08-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariga', '0009_alter_comments_comment_alter_projects_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='languages',
            field=models.ManyToManyField(db_column='language', to='mariga.Languages'),
        ),
    ]
