# Generated by Django 4.0.2 on 2022-08-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariga', '0010_alter_projects_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='languages',
            field=models.ManyToManyField(db_column='languages_language', to='mariga.Languages'),
        ),
    ]
